# Generated by Django 5.1.1 on 2024-09-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_users_user_email_6f2530_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_types', models.JSONField(default=list)),
                ('risk_profiles', models.JSONField(default=list)),
                ('themes', models.JSONField(default=list)),
                ('investment_duration', models.CharField(blank=True, max_length=100)),
                ('expected_returns', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='users_userp_user_id_355e4b_idx')],
            },
        ),
    ]
