# Generated by Django 5.1.1 on 2024-09-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundfolio',
            name='current_value',
        ),
    ]
