# Generated by Django 5.1.1 on 2024-09-21 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_fund_funds_fund_id_19787b_idx'),
        ('portfolios', '0004_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundfolio',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fundfolio',
            name='units_held',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['portfolio'], name='portfolios__portfol_ddee88_idx'),
        ),
        migrations.AddIndex(
            model_name='fundfolio',
            index=models.Index(fields=['folio'], name='portfolios__folio_i_4fcb69_idx'),
        ),
        migrations.AddIndex(
            model_name='fundfolio',
            index=models.Index(fields=['fund'], name='portfolios__fund_id_a9ce24_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='portfolios__user_id_31c861_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='portfolios__user_id_18aa1e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fund'], name='portfolios__fund_id_60c2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio'], name='portfolios__portfol_68988f_idx'),
        ),
    ]
