# Generated by Django 5.1.1 on 2024-09-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='folios',
            field=models.ManyToManyField(related_name='funds', through='portfolios.FundFolio', to='portfolios.folio'),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fundtype'),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.riskprofile'),
        ),
        migrations.AddField(
            model_name='fund',
            name='themes',
            field=models.ManyToManyField(to='funds.theme'),
        ),
    ]
