# Generated by Django 5.1.1 on 2024-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_initial'),
        ('portfolios', '0004_transaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['id'], name='funds_fund_id_19787b_idx'),
        ),
    ]
